'use client'
import { createContext,useContext,useEffect,useMemo,useRef,useState } from 'react'; import { config } from '@/lib/config'; import type { NowPlaying, Track } from '@/lib/media-types'
type Status='idle'|'loading'|'playing'|'paused'|'error'; type MediaCtx={nowPlaying:NowPlaying|null; track:Track|undefined; mediaStatus:Status; volume:number; isMuted:boolean; play:()=>Promise<void>; pause:()=>void; toggle:()=>Promise<void>; setVolume:(v:number)=>void; toggleMute:()=>void}
const Context=createContext<MediaCtx|null>(null)
export function MediaProvider({children}:{children:React.ReactNode}){const audio=useRef<HTMLAudioElement|null>(null);const [nowPlaying,setNowPlaying]=useState<NowPlaying|null>(null);const [mediaStatus,setMediaStatus]=useState<Status>('idle');const [volume,setVolumeState]=useState(.85);const [isMuted,setMuted]=useState(false)
 useEffect(()=>{const el=new Audio();el.preload='none';el.src=config.radioStream;el.volume=.85;audio.current=el;const onPlay=()=>setMediaStatus('playing'),onPause=()=>setMediaStatus('paused'),onErr=()=>setMediaStatus('error');el.addEventListener('playing',onPlay);el.addEventListener('pause',onPause);el.addEventListener('error',onErr);return()=>{el.pause();el.removeEventListener('playing',onPlay);el.removeEventListener('pause',onPause);el.removeEventListener('error',onErr);audio.current=null}},[])
 useEffect(()=>{let cancelled=false;const poll=async()=>{try{const r=await fetch(config.nowPlaying,{cache:'no-store'});if(!r.ok)throw new Error();const data=await r.json();if(!cancelled)setNowPlaying(data)}catch{} };poll();const id=window.setInterval(poll,20000);return()=>{cancelled=true;clearInterval(id)}},[])
 useEffect(()=>{const track=nowPlaying?.now_playing?.song;if(!track||typeof navigator==='undefined'||!('mediaSession' in navigator))return; navigator.mediaSession.metadata=new MediaMetadata({title:track.title??track.text??'MediaCenter Radio',artist:track.artist??'Unified-Live',album:track.album??'MediaCenter',artwork:track.art?[{src:track.art,sizes:'512x512'}]:[]});const play=()=>void audio.current?.play(),pause=()=>audio.current?.pause(),stop=()=>{audio.current?.pause();if(audio.current)audio.current.currentTime=0};navigator.mediaSession.setActionHandler('play',play);navigator.mediaSession.setActionHandler('pause',pause);navigator.mediaSession.setActionHandler('stop',stop)},[nowPlaying])
 const value=useMemo<MediaCtx>(()=>({nowPlaying,track:nowPlaying?.now_playing?.song,mediaStatus,volume,isMuted,play:async()=>{if(!audio.current)return;setMediaStatus('loading');try{await audio.current.play()}catch{setMediaStatus('error')}},pause:()=>audio.current?.pause(),toggle:async()=>{if(audio.current?.paused)await (async()=>{try{await audio.current!.play()}catch{setMediaStatus('error')}})();else audio.current?.pause()},setVolume:(v)=>{setVolumeState(v);if(audio.current)audio.current.volume=v},toggleMute:()=>{setMuted(v=>{if(audio.current)audio.current.muted=!v;return !v})}}),[nowPlaying,mediaStatus,volume,isMuted]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useMedia(){const value=useContext(Context);if(!value)throw new Error('useMedia must be used within MediaProvider');return value}
